/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LootRealmsLockbox } from "./LootRealmsLockbox";

export { LootRealmsLockbox__factory } from "./factories/LootRealmsLockbox__factory";
